# Generated by Django 5.2.6 on 2025-10-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentevent_id_alter_paymentevent_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentevent',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
